---
version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tuber

  frontend:
    build: ./frontend
    image: ghcr.io/magfest/tuber-frontend:latest
    networks:
      - tuber

  backend:
    build: ./backend
    ports:
      - 8080:8080
    image: ghcr.io/${REPO_NAME:-magfest/tuber}-backend:latest
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg://tuber:tuber@postgres/tuber
      REDIS_URL: redis://redis:6379/0
      VERBOSE: "true"
      FLASK_DEBUG: 1
      WORKERS: 4
      CIRCUITBREAKER_THREADS: 4
      ENABLE_CIRCUITBREAKER: true
      CIRCUITBREAKER_TIMEOUT: 1
    # scale: 1
    networks:
      - tuber

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=tuber
      - POSTGRES_USER=tuber
      - POSTGRES_DB=tuber
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tuber

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - tuber

networks:
  tuber:

volumes:
  db-data:
